### ISSUE TITLE
gig 도움말 화면에서 template 리스트 보여줄 때 정렬이 되서 보여주면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by yhbyun** [hackrslab/gig#3]
git 도움말 화면에서 template 리스트를 뿌려주는 데 정렬이 안되어 있어서 찾기가 불편하네요. 정렬 기능 추가 좀 해주실 수 없나요?

**Comment by insanehong** [comment]
알파벳순으로요?

아니면 사용자 커스텀 템플릿과 gig 지원을 구분하는게 좋을가요?

나의 iPhone에서 보냄

2015. 4. 7. 오후 6:38 YongHun Byun <notifications@github.com> 작성:

**Comment by insanehong** [comment]
patch in 397cbbbc782ff71a98629e4db7676f767ee12f91

Thanks :-)
